---
abstract: 'Reference implementation of the TAP specification'
author:
  - 'Andrew Rodland <arodland@cpan.org>'
build_requires:
  Carp: 0
  Path::Class: 0
  Test::More: 0
  YAML::Any: 0
  YAML::XS: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-Spec-Parser
requires:
  Method::Signatures::Simple: 0
  Mouse: 0
  Mouse::Util::TypeConstraints: 0
  MouseX::Foreign: 0
  Try::Tiny: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/arodland/TAP-Spec-Parser.git
version: 0.05
